image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

stages:
  - test

cypress-tests:
  stage: test
  script:
    - npm install 
    - $(npm bin)/cypress run --headless --browser chrome

  artifacts:
    paths:
      - cypress/screenshots
    expire_in: 1 day