image: cypress/base:14

stages:
  - test

cypress-tests:
  stage: test
  script:
    - npm install 
    - npx cypress --headless --browser chrome run

  artifacts:
    paths:
      - cypress/screenshots
    expire_in: 1 day